/**
 * Evolver 集成脚本
 * 将 Claude Code 日志与 Evolver 连接
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { runEvolverAnalysis, generateClaudeCodeGenes, generateClaudeCodeCapsules } from './index';

// Evolver 目录
const EVOLVER_DIR = path.resolve(__dirname, '../../evolver');

// Claude Code 配置目录
const CLAUDE_DIR = process.env.CLAUDE_DIR || path.join(process.env.USERPROFILE || process.env.HOME || '', '.claude');

interface IntegrationConfig {
  evolverDir: string;
  claudeDir: string;
  outputDir: string;
  autoRun?: boolean;
}

/**
 * 合并 Genes 到 Evolver
 */
function mergeGenes(evolverDir: string, newGenes: any[]): void {
  const genesPath = path.join(evolverDir, 'assets/gep/genes.json');

  let genesData: { version: number; genes: any[] } = { version: 1, genes: [] };
  if (fs.existsSync(genesPath)) {
    const content = fs.readFileSync(genesPath, 'utf-8');
    const parsed = JSON.parse(content);
    // 兼容两种格式：数组或对象
    if (Array.isArray(parsed)) {
      genesData = { version: 1, genes: parsed };
    } else {
      genesData = parsed;
    }
  }

  // 合并，避免重复
  const existingIds = new Set(genesData.genes.map((g: any) => g.id));
  for (const gene of newGenes) {
    // 转换为 Evolver 格式
    const evolverGene = {
      type: 'Gene',
      id: gene.id,
      category: 'claude-code',
      signals_match: gene.triggers.map((t: string) => t.toLowerCase()),
      preconditions: [`Signal matches: ${gene.triggers.join(', ')}`],
      strategy: gene.actions,
      validation: gene.validation || []
    };

    if (!existingIds.has(gene.id)) {
      genesData.genes.push(evolverGene);
      console.log(`  + Added gene: ${gene.id}`);
    } else {
      console.log(`  = Gene already exists: ${gene.id}`);
    }
  }

  fs.writeFileSync(genesPath, JSON.stringify(genesData, null, 2), 'utf-8');
}

/**
 * 合并 Capsules 到 Evolver
 */
function mergeCapsules(evolverDir: string, newCapsules: any[]): void {
  const capsulesPath = path.join(evolverDir, 'assets/gep/capsules.json');

  let capsulesData: { version: number; capsules: any[] } = { version: 1, capsules: [] };
  if (fs.existsSync(capsulesPath)) {
    const content = fs.readFileSync(capsulesPath, 'utf-8');
    const parsed = JSON.parse(content);
    // 兼容两种格式：数组或对象
    if (Array.isArray(parsed)) {
      capsulesData = { version: 1, capsules: parsed };
    } else {
      capsulesData = parsed;
    }
  }

  // 合并，避免重复
  const existingIds = new Set(capsulesData.capsules.map((c: any) => c.id));
  for (const capsule of newCapsules) {
    // 转换为 Evolver 格式
    const evolverCapsule = {
      type: 'Capsule',
      id: capsule.id,
      name: capsule.name,
      genes: capsule.genes,
      context: capsule.context
    };

    if (!existingIds.has(capsule.id)) {
      capsulesData.capsules.push(evolverCapsule);
      console.log(`  + Added capsule: ${capsule.id}`);
    } else {
      console.log(`  = Capsule already exists: ${capsule.id}`);
    }
  }

  fs.writeFileSync(capsulesPath, JSON.stringify(capsulesData, null, 2), 'utf-8');
}

/**
 * 将转换后的日志复制到 Evolver 的 logs 目录
 */
function copyLogsToEvolver(outputDir: string, evolverDir: string): void {
  const sourceLog = path.join(outputDir, 'evolver-log.jsonl');
  const targetDir = path.join(evolverDir, 'logs');

  // 创建目标目录
  fs.mkdirSync(targetDir, { recursive: true });

  // 复制日志
  const targetLog = path.join(targetDir, 'claude-code-signals.jsonl');
  if (fs.existsSync(sourceLog)) {
    fs.copyFileSync(sourceLog, targetLog);
    console.log(`  Copied logs to: ${targetLog}`);
  }
}

/**
 * 创建 Evolver 的 memory 目录结构
 */
function createMemoryStructure(evolverDir: string): void {
  const memoryDir = path.join(evolverDir, 'memory');
  const evolutionDir = path.join(memoryDir, 'evolution');

  fs.mkdirSync(evolutionDir, { recursive: true });

  // 创建初始的进化叙事文件
  const narrativePath = path.join(evolutionDir, 'evolution_narrative.md');
  if (!fs.existsSync(narrativePath)) {
    fs.writeFileSync(narrativePath, `# Claude Code Evolution Narrative

This file tracks the evolution history of Claude Code configurations and prompts.

## Initial State
- Created by evolver-adapter integration
- Source: Claude Code debug logs and history

`, 'utf-8');
    console.log(`  Created: ${narrativePath}`);
  }
}

/**
 * 创建环境配置文件
 */
function createEnvFile(evolverDir: string, config: IntegrationConfig): void {
  const envPath = path.join(evolverDir, '.env');

  const envContent = `# Evolver Configuration for Claude Code
# Generated by evolver-adapter

# Claude Code 日志目录
EVOLVER_LOGS_DIR=${path.join(evolverDir, 'logs')}

# Memory 目录
MEMORY_DIR=${path.join(evolverDir, 'memory')}

# GEP 资产目录
GEP_ASSETS_DIR=${path.join(evolverDir, 'assets/gep')}

# 仓库根目录
EVOLVER_REPO_ROOT=${evolverDir}

# 进化策略 (balanced, innovate, harden, repair-only)
EVOLVE_STRATEGY=balanced

# Claude Code 日志源
CLAUDE_DIR=${config.claudeDir}
`;

  fs.writeFileSync(envPath, envContent, 'utf-8');
  console.log(`  Created: ${envPath}`);
}

/**
 * 运行完整的集成流程
 */
export function integrate(config: Partial<IntegrationConfig> = {}): void {
  // 先计算 evolverDir，因为 outputDir 依赖它
  const evolverDir = config.evolverDir || EVOLVER_DIR;
  const claudeDir = config.claudeDir || CLAUDE_DIR;
  const outputDir = config.outputDir || path.join(path.dirname(evolverDir), 'evolver-output');

  const finalConfig: IntegrationConfig = {
    evolverDir,
    claudeDir,
    outputDir,
    autoRun: config.autoRun
  };

  console.log('=== Evolver Integration ===\n');
  console.log(`Evolver directory: ${finalConfig.evolverDir}`);
  console.log(`Claude directory: ${finalConfig.claudeDir}`);
  console.log(`Output directory: ${finalConfig.outputDir}\n`);

  // 1. 检查 Evolver 目录
  if (!fs.existsSync(finalConfig.evolverDir)) {
    console.error('Error: Evolver directory not found!');
    console.error('Please clone Evolver first:');
    console.error('  git clone https://github.com/EvoMap/evolver.git');
    return;
  }

  // 2. 运行日志分析
  console.log('1. Analyzing Claude Code logs...');
  runEvolverAnalysis({
    outputDir: finalConfig.outputDir,
    generatePrompt: true
  });

  // 3. 合并 Genes
  console.log('\n2. Merging Genes...');
  const genes = generateClaudeCodeGenes();
  mergeGenes(finalConfig.evolverDir, genes);

  // 4. 合并 Capsules
  console.log('\n3. Merging Capsules...');
  const capsules = generateClaudeCodeCapsules();
  mergeCapsules(finalConfig.evolverDir, capsules);

  // 5. 复制日志
  console.log('\n4. Copying logs to Evolver...');
  copyLogsToEvolver(finalConfig.outputDir, finalConfig.evolverDir);

  // 6. 创建 Memory 结构
  console.log('\n5. Creating memory structure...');
  createMemoryStructure(finalConfig.evolverDir);

  // 7. 创建环境配置
  console.log('\n6. Creating environment configuration...');
  createEnvFile(finalConfig.evolverDir, finalConfig);

  console.log('\n=== Integration Complete ===');
  console.log('\nNext steps:');
  console.log(`  1. cd ${finalConfig.evolverDir}`);
  console.log('  2. npm install');
  console.log('  3. node index.js');
  console.log('\nOr run with loop mode:');
  console.log('  node index.js --loop');
}

/**
 * 运行 Evolver
 */
export function runEvolver(evolverDir: string = EVOLVER_DIR, loop: boolean = false): void {
  console.log('Running Evolver...\n');

  const args = loop ? ' --loop' : '';

  try {
    execSync(`node index.js${args}`, {
      cwd: evolverDir,
      stdio: 'inherit',
      env: {
        ...process.env,
        EVOLVER_REPO_ROOT: evolverDir
      }
    });
  } catch (error) {
    console.error('Evolver execution failed:', error);
  }
}

// CLI 入口
if (require.main === module) {
  const args = process.argv.slice(2);
  const command = args[0];

  if (command === 'run') {
    const loop = args.includes('--loop');
    runEvolver(EVOLVER_DIR, loop);
  } else {
    // 默认执行集成
    const evolverDir = args.find(a => a.startsWith('--evolver='))?.split('=')[1];
    integrate({ evolverDir });
  }
}

export default {
  integrate,
  runEvolver,
  mergeGenes,
  mergeCapsules
};
